### ISSUE TITLE
"author" is not from "owner"

### ISSUE THREAD

**Issue by alfredk23** [kanesee/openair#14]
When a resource is displayed, it shows e.g. "by Kristina Toutanova from Stanford University", where in the resource editing dialog "Kristina Toutanova" is entered as the author and "Stanford University" as the owner. I believe often author is not from owner institution or we do not know for sure if this is the case. I think it would be better to say just author:x, owner:y, or "by x for y".

**Comment by alfredk23** [comment]
More to this: I found a couple of cases where the author is also the owner, so it sounds like "by Christian Muise from Christian Muise"

**Comment by snminton** [comment]
good catch, thanks

**Comment by kanesee** [comment]
decision is to move owner to the far right of the page

**Comment by kanesee** [comment]
resolved
