### ISSUE TITLE
Cannot find resource titled "Ms. Pac-Man Framework"

### ISSUE THREAD

**Issue by alfredk23** [kanesee/openair#16]
Search with the above title returns 131 results. Following the Advanced Search Tips and modifying the search as "+Ms. +Pac-+Man +Framework" also returns 131 results. This resource is under "Games and puzzles" and can be found by scrolling through the list. May be fixing this case can also fix similar problems.

**Comment by kanesee** [comment]
Just looked into it. I think I understand the issue. We're leveraging Mysql Full-Text boolean search. By default, Mysql does not index any words that are 3 or less characters. So what's happening here is that "Ms.", "Pac", and "Man" aren't even part of the search.

This can easily be rectified by modifying the mysql settings
(https://dev.mysql.com/doc/refman/5.1/en/fulltext-fine-tuning.html)
[mysqld]
ft_min_word_len=3

Only question that remains is what is the minimum number of characters that a word must have to be indexed and searchable

**Comment by alfredk23** [comment]
I think 2 characters is a min. We have SVM, DM, C5, etc. But then in may pick up the stopwords, such as and, at etc., unless these words can be somehow excluded. There are lists of common stopwords (I can send one if needed).

**Comment by snminton** [comment]
2?

**Comment by kanesee** [comment]
Ok, I will work on this when my other tasks free up a bit

**Comment by kanesee** [comment]
Fixed

**Comment by snminton** [comment]
Thx
